trigger:
- main  # Run the pipeline on pushes to the 'main' branch

stages:
# 🔹 Build Stage
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Function App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # Use Node.js 18 (or latest)
    - script: |
        npm install
      displayName: 'Install Dependencies'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'  # Archive all source files
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true
    - publish: $(Build.ArtifactStagingDirectory)/functionapp.zip
      artifact: functionapp

# 🔹 Test Stage
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        npm test
      displayName: 'Run Tests'

# 🔹 Deploy Stage
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Function'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'Azure-Connection'   # Replace with your Azure Service Connection
        appType: 'functionApp'
        appName: 'myAzureFunctionApp'           # Replace with your Function App name
        package: '$(Pipeline.Workspace)/functionapp/functionapp.zip'
